name: 'Upload'
description: 'Upload'

runs:
  using: "composite"
  steps:
  - name: Setup Env variables
    shell: bash
    id: envs
    run: |
      ARCH=$(uname -m)
      echo "arch=$ARCH" >> $GITHUB_OUTPUT
  - name: Upload nexus Linux
    uses: actions/upload-artifact@v4
    if: ${{ runner.os == 'Linux' }}
    with:
      name: nexus-linux-${{ steps.envs.outputs.arch }}
      path: install/nexus-linux-${{ steps.envs.outputs.arch }}.tar.gz
  - name: Upload nxsview MacOS
    uses: actions/upload-artifact@v4
    if: ${{ runner.os == 'macOS' }}
    with:
      name: nxsview-macos-${{ steps.envs.outputs.arch }}
      path: install/nxsview-macos-${{ steps.envs.outputs.arch }}.tar.gz
  - name: Uploading Nexus Windows
    uses: actions/upload-artifact@v4
    if: ${{ runner.os == 'Windows' }}
    with:
      name: nexus-windows-${{ steps.envs.outputs.arch }}
      path: install/nexus-windows-${{ steps.envs.outputs.arch }}.zip