name: Windows

on:
  [push, pull_request]
  
jobs:
  linux_build:
    name: Build Nexus (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: true
        version: '5.15.2'
    - name: Install dependencies
      run: |
       cd ..
       git clone --single-branch --branch devel https://github.com/cnr-isti-vclab/vcglib
       echo "VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC" >> $GITHUB_ENV
    - name: Configure and Build
      shell: bash
      run: |
        mkdir build
        mkdir install
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_INSTALL_PREFIX=../install ..
        ninja
        ninja install
    - name: Deploy
      shell: bash
      run: |
        cd install/bin
        windeployqt nxsview.exe
        cd ..
        mv bin nexus_portable
    - name: Uploading Nexus Portable
      uses: actions/upload-artifact@v4
      with:
        name: nexus_windows_portable
        path: install/nexus_portable
